# Generated by Django 3.1.7 on 2021-04-01 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=50, verbose_name='Детальный адрес')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Meets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meet_Date', models.DateField(verbose_name='Дата встречи')),
                ('Meet_Location', models.TextField(verbose_name='Место встречи')),
                ('Meet_Score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговые баллы')),
                ('Other_Details', models.TextField(blank=True, verbose_name='Прочие детали встречи')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University_Name', models.CharField(max_length=100, verbose_name='Название Университета')),
                ('Other_Details', models.TextField(blank=True, verbose_name='Прочие детали')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
        migrations.CreateModel(
            name='University_Meet_Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Overall_University_Scores', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общие баллы Университета')),
                ('Meet_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.meets', verbose_name='Встреча')),
                ('University_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Университетская встреча',
                'verbose_name_plural': 'Университетские встречи',
            },
        ),
        migrations.CreateModel(
            name='Gymnasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gymnast_Name', models.CharField(max_length=50, verbose_name='Имя гимнаста')),
                ('Gymnast_Hometown', models.CharField(max_length=50, verbose_name='Родной город')),
                ('Gymnast_Photo', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото')),
                ('Other_Gymnast_Details', models.TextField(blank=True, verbose_name='Детали')),
                ('Gymnast_Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.addresses')),
                ('University_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.university')),
            ],
            options={
                'verbose_name': 'Гимнаст',
                'verbose_name_plural': 'Гимнасты',
            },
        ),
    ]
