# Generated by Django 3.1.7 on 2021-03-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymnasts',
            name='Gymnast_Address',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='gymnasts',
            name='Gymnast_Hometown',
            field=models.CharField(max_length=50, verbose_name='Родной город'),
        ),
        migrations.AlterField(
            model_name='gymnasts',
            name='Gymnast_Name',
            field=models.CharField(max_length=50, verbose_name='Имя гимнаста'),
        ),
        migrations.AlterField(
            model_name='gymnasts',
            name='Other_Gymnast_Details',
            field=models.TextField(blank=True, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='meets',
            name='Other_Details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='Other_Details',
            field=models.TextField(blank=True, verbose_name='Прочие детали'),
        ),
        migrations.AlterField(
            model_name='university',
            name='University_Name',
            field=models.CharField(max_length=100, verbose_name='Название Университета'),
        ),
    ]
