# Generated by Django 3.1.7 on 2021-04-20 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210402_1500'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gymnasts',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='gymnasts',
            name='Gymnast_Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.addresses', verbose_name='Адрес гимнаста'),
        ),
        migrations.AlterField(
            model_name='gymnasts',
            name='Gymnast_Photo',
            field=models.ImageField(upload_to='photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='gymnasts',
            name='University_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.university', verbose_name='Университет'),
        ),
    ]
