# Generated by Django 3.1.7 on 2021-03-31 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210331_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members_Addresses',
            new_name='Gymnasts_Addresses',
        ),
        migrations.AlterField(
            model_name='addresses',
            name='Address_Details',
            field=models.TextField(verbose_name='Детальный адрес'),
        ),
        migrations.AlterField(
            model_name='gymnasts',
            name='Gymnast_Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.addresses'),
        ),
    ]
