# Generated by Django 3.1.7 on 2021-03-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210331_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymnasts',
            name='Gymnast_Address',
        ),
        migrations.AddField(
            model_name='gymnasts',
            name='Gymnast_Address',
            field=models.ManyToManyField(to='mainapp.Addresses', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='gymnasts',
            name='Gymnast_Photo',
            field=models.ImageField(upload_to='photos', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='Gymnasts_Addresses',
        ),
    ]
