# Generated by Django 3.1.7 on 2021-03-31 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210331_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gymnasts_Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.addresses', verbose_name='Адрес')),
                ('Gymnasts_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.gymnasts', verbose_name='Гимнаст')),
            ],
            options={
                'verbose_name': 'Адрес Участника',
                'verbose_name_plural': 'Адреса Участников',
                "db_table": "gymnasts_addresses_gymnasts",
            },
        ),
        migrations.AlterField(
            model_name='gymnasts',
            name='Gymnast_Address',
            field=models.ManyToManyField(through='mainapp.Gymnasts_Addresses', to='mainapp.Addresses', verbose_name='Адрес'),
        ),
    ]
