# Generated by Django 3.1.7 on 2021-03-31 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210331_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymnasts_addresses',
            name='Gymnasts_ID',
        ),
        migrations.AddField(
            model_name='gymnasts_addresses',
            name='Gymnast_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.gymnasts', verbose_name='Гимнаст'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='Address_Details',
            field=models.CharField(max_length=100, verbose_name='Детальный адрес'),
        ),
        migrations.AlterField(
            model_name='gymnasts_addresses',
            name='Address_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.addresses', verbose_name='Адрес'),
        ),
    ]
