# Generated by Django 3.1.7 on 2021-03-31 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210401_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymnasts_addresses',
            options={},
        ),
        migrations.RemoveField(
            model_name='gymnasts_addresses',
            name='number',
        ),
        migrations.AddField(
            model_name='gymnasts',
            name='Gymnast_Address',
            field=models.ManyToManyField(to='mainapp.Addresses'),
        ),
        migrations.AddField(
            model_name='gymnasts_addresses',
            name='Address_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.gymnasts'),
        ),
        migrations.AddField(
            model_name='gymnasts_addresses',
            name='Gymnast_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.addresses'),
        ),
    ]
