# Generated by Django 3.1.7 on 2021-03-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210401_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymnasts_addresses',
            options={'verbose_name': 'Адрес Участника', 'verbose_name_plural': 'Адреса Участников'},
        ),
        migrations.AlterField(
            model_name='gymnasts',
            name='Gymnast_Address',
            field=models.ManyToManyField(through='mainapp.Gymnasts_Addresses', to='mainapp.Addresses'),
        ),
    ]
