# Generated by Django 3.1.7 on 2021-03-31 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210401_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnasts_addresses',
            name='Address_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.addresses'),
        ),
        migrations.AlterField(
            model_name='gymnasts_addresses',
            name='Gymnast_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.gymnasts'),
        ),
    ]
