# Generated by Django 3.1.7 on 2021-03-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210401_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnasts',
            name='Gymnast_Address',
            field=models.ManyToManyField(through='mainapp.Gymnasts_Addresses', to='mainapp.Addresses'),
        ),
    ]
