# Generated by Django 3.1.7 on 2021-03-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210401_0214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gymnasts_Addresses',
            new_name='Addresses_Gymnasts',
        ),
        migrations.AlterField(
            model_name='gymnasts',
            name='Gymnast_Address',
            field=models.ManyToManyField(to='mainapp.Addresses'),
        ),
        migrations.AlterModelTable(
            name='addresses_gymnasts',
            table=None,
        ),
    ]
