# Generated by Django 3.1.7 on 2021-03-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.IntegerField(verbose_name='Номер Тел. Покупателя')),
                ('customer_email', models.TextField(verbose_name='Почта')),
                ('customer_addres', models.TextField(verbose_name='Адрес покупателя')),
                ('customer_payment_method_details', models.TextField(null=True, verbose_name='Способ оплаты покупателя')),
            ],
            options={
                'verbose_name': 'Покупатели',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='RefEventTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Описание событий',
                'verbose_name_plural': 'Описание событий',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(verbose_name='Название события')),
                ('event_start_date', models.DateField(null=True, verbose_name='Время начало события')),
                ('event_end_date', models.DateField(null=True, verbose_name='Время конец события')),
                ('event_type_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.refeventtypes')),
            ],
            options={
                'verbose_name': 'События',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='EventReservartions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_datetime', models.DateField(null=True, verbose_name='Дата события')),
                ('booking_made_date', models.DateField(null=True, verbose_name='Дата бронирования')),
                ('booking_seat_count', models.IntegerField(null=True, verbose_name='Количество мест')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customers')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.events')),
            ],
            options={
                'verbose_name': 'Резервирование событий',
                'verbose_name_plural': 'Резервирование событий',
            },
        ),
        migrations.CreateModel(
            name='EventRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_datetime', models.DateField(null=True, verbose_name='Дата события')),
                ('booking_made_date', models.DateField(null=True, verbose_name='Дата бронирования')),
                ('booking_seat_count', models.IntegerField(null=True, verbose_name='Количество мест')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customers')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.events')),
            ],
            options={
                'verbose_name': 'Регистрации на мероприятия',
                'verbose_name_plural': 'Регистрации на мероприятия',
            },
        ),
    ]
