# Generated by Django 3.1.7 on 2021-03-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_addres',
            field=models.CharField(max_length=100, verbose_name='Адрес покупателя'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_email',
            field=models.CharField(max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_payment_method_details',
            field=models.CharField(max_length=100, null=True, verbose_name='Способ оплаты покупателя'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(max_length=100, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='refeventtypes',
            name='event_type_description',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
    ]
