# Generated by Django 3.1.7 on 2021-04-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_myadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAdmin',
        ),
    ]
